name: create PR
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
  workflow_dispatch:
  # FIXME: uncomment
  # push:
  #   tags:
  #   - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-pr:
    name: create pr
    runs-on: ubuntu-latest
    
    steps:
    - name: create Pull Request to another-repo
      run: |
        gh pr create \
        --title "Test PR " \
        --body "body" \
        --repo yu9824/mymemo \
        --base main \
        --head feature/update-graphql-schema \
        --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
    env:
      GH_TOKEN: ${{ github.token }}
